# Generated by Django 5.1.1 on 2024-09-19 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysubjectsmodel',
            name='first',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first', to='groups.subjectmodel'),
        ),
        migrations.AlterField(
            model_name='dailysubjectsmodel',
            name='second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second', to='groups.subjectmodel'),
        ),
        migrations.AlterField(
            model_name='dailysubjectsmodel',
            name='third',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third', to='groups.subjectmodel'),
        ),
    ]
