# Generated by Django 5.1.1 on 2024-09-19 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_dailysubjectsmodel_first_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysubjectsmodel',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.groupmodel'),
        ),
    ]
